on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target:
          - arch: amd64
            triplet: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cache `chroot` environment
        id: cache-chroot-root
        uses: actions/cache@v3
        with:
          path: john-shaffer/cache@main
          key: chroot-root-${{ matrix.target.triplet }}
      - name: Bootstrap `chroot` environment
        if: ${{ steps.cache-chroot-root.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y debootstrap

          sudo debootstrap --arch=${{ matrix.target.arch }} --variant=minbase bionic /chroot-root

          CARGO_CONFIG="$(printf "\
          [build] \n\
          rustflags = [ \n\
              \"-C\", \"embed-bitcode=off\" \n\
          ] \n\
          [profile.dev] \n\
          lto = \"off\" \
          ")"

          SCRIPT="$(printf "\
          apt-get update -y &&\
          apt-get install -y \
            curl \
            pkg-config gcc \
            libudev-dev libxkbcommon-dev &&\
          \
          curl -sSf https://sh.rustup.rs | bash -s -- \
            -y \
            --default-toolchain=nightly \
            --profile=minimal &&\
          source /root/.cargo/env &&\
          echo \"$CARGO_CONFIG\" > /root/.cargo/config &&\
          \
          curl -L https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.2375+771d07268.tar.xz -o zig.tar.xz &&\
          tar -xf -C $HOME zig.tar.xz &&\
          rm zig.tar.xz &&\
          mv $HOME/zig-* $HOME/zig &&\
          cargo install cargo-zigbuild \
          ")"

          sudo chroot /chroot-root /bin/bash -c "$SCRIPT"
